### ISSUE TITLE
Ubuntu 22.04 container image

### ISSUE THREAD

**Issue by kyleconroy** [buildbuddy-io/buildbuddy#4157]
Workflows currently supports `ubuntu-18.04` and `ubuntu-20.04`. Would it be possible to add a `ubuntu-22.04` image as well? We're running into an issue where a set of rules we use needs a newer version of curl than the one 20.04 provides.

```
actions:
  - name: "Test all targets"
    container_image: "ubuntu-20.04"
    triggers:
      push:
        branches:
          - "main" # <-- replace "main" with your main branch name
      pull_request:
        branches:
          - "*"
    user: "buildbuddy"
    bazel_commands:
      - "test //..."
```
