### ISSUE TITLE
Storage space isn't pruned (at least not fast enough).

### ISSUE THREAD

**Issue by ppand** [buildbuddy-io/buildbuddy#7073]
**Describe the bug**
Storage space isn't getting cleared after configured storage.ttl_seconds and we are running out of diskspace.

**To Reproduce**
We are running gcr.io/flame-public/buildbuddy-app-onprem:v2.74.0 with following configuration.

```
storage:
  enable_chunked_event_logs: true
  cleanup_batch_size: 10
  ttl_seconds: 432000 # Five days in seconds.
  disk:
    root_directory: /tmp/buildbuddy-storage
cache:
  max_size_bytes: 429496729600 # 400 GB
  disk:
    root_directory: /tmp/buildbuddy-cache
remote_execution:
  enable_remote_exec: false

```

But there are still entries that are older than 30 days. In our CI env, we have ~200 builds each working day with each build using roughly around 30 bazel invocations. 

Wondering if cleanup_batch_size of 10 is too small in our case. Also noticed, even though docker process is started by a non-root user, all the files in /tmp/buildbuddy-storage seem to be owned by root. Does that affect pruning ?

**Expected behavior**
All entries in storage older than 5 days are pruned

- OS: Linux

**Additional context**
