### ISSUE TITLE
Go panic after hitting thread limits

### ISSUE THREAD

**Issue by Sh4d1** [buildbuddy-io/buildbuddy#9053]
Hello! Our self hosted buildbuddy instance (in docker, with `gcr.io/flame-public/buildbuddy-app-onprem:v2.151.0` , is kinda panicking a lot (once or twice a day), with this:

```
2025-04-24T07:21:44.043355424Z runtime: program exceeds 10000-thread limit
2025-04-24T07:21:44.043367416Z fatal error: thread exhaustion
[2 millions line more, basically all goroutines stack trace]
```

Is this expected? Any ideas why? (too much pressure on the cache?)

**Comment by sluongng** [comment]
It's the default limit of Go runtime on the number of OS-thread (not to be confused with goroutines) the program can use.
This doc comes with some explanation https://pkg.go.dev/runtime/debug#SetMaxThreads

As for why is it happening on your machine, it's hard to say without additional information.
Could you store the stack dump in a file and share it here? What is the spec of the underlying system? Which configuration flags are you using?

**Comment by Sh4d1** [comment]
Yep I'm familiar with the go runtime :D (i was talking about goroutines cause their stacks get dumps on a panic, and I guess there are a lot of goroutines for that number of os thread 😅 ), I was rather wondering if it makes sense with how buildbuddy is working (maybe it's just too many jobs for a single instance? Though I never saw this issue with bazel-remote cache we used to have) 

So, here is our config:
```
app:
  build_buddy_url: "<buildbuddy URL>"
  expanded_suggestions_enabled: true
  usage_enabled: true
  log_level: debug
database:
  data_source: "sqlite3:///buildbuddy.db"
storage:
  ttl_seconds: 2592000 # 30 days in seconds.
  chunk_file_size_bytes: 3000000 # 3 MB
  disk:
    root_directory: /buildbuddy
  aws_s3:
    region: eu-west-3
    bucket: amo-buildbuddy
cache:
  detailed_stats_enabled: true
  max_size_bytes: 700000000000 # 700G
  disk:
    root_directory: /buildbuddy-cache
github:
  access_token: <token>
```

The machine is a 8 core (Intel(R) Xeon(R) Platinum 8488C) with 32G of ram.

You can found the stacktrace here: https://easyupload.io/a6860k 

Thanks!
